import type { ToolDefinition } from "../../definition.js";
import {
  listGroupsTool,
  getGroupTool,
  createGroupTool,
  updateGroupTool,
  deleteGroupTool,
} from "./crud.js";
import {
  listGroupMembersTool,
  addGroupMembersByUsernameTool,
  addGroupMembersByUserIdTool,
  addGroupMembersByEmailTool,
  inviteGroupMembersByEmailTool,
  removeGroupMembersByUsernameTool,
  removeGroupMembersByUserIdTool,
  removeGroupMembersByEmailTool,
  addGroupOwnersByUsernameTool,
  addGroupOwnersByUserIdTool,
  addGroupOwnersByEmailTool,
  removeGroupOwnersByUsernameTool,
  removeGroupOwnersByUserIdTool,
  removeGroupOwnersByEmailTool,
} from "./members.js";
import {
  listGroupMembershipRequestsTool,
  handleGroupMembershipRequestTool,
  requestGroupMembershipTool,
  joinGroupTool,
  leaveGroupTool,
} from "./requests.js";

export {
  listGroupsTool,
  getGroupTool,
  createGroupTool,
  updateGroupTool,
  deleteGroupTool,
  listGroupMembersTool,
  addGroupMembersByUsernameTool,
  addGroupMembersByUserIdTool,
  addGroupMembersByEmailTool,
  inviteGroupMembersByEmailTool,
  removeGroupMembersByUsernameTool,
  removeGroupMembersByUserIdTool,
  removeGroupMembersByEmailTool,
  addGroupOwnersByUsernameTool,
  addGroupOwnersByUserIdTool,
  addGroupOwnersByEmailTool,
  removeGroupOwnersByUsernameTool,
  removeGroupOwnersByUserIdTool,
  removeGroupOwnersByEmailTool,
  listGroupMembershipRequestsTool,
  handleGroupMembershipRequestTool,
  requestGroupMembershipTool,
  joinGroupTool,
  leaveGroupTool,
};

export const groupTools = [
  listGroupsTool,
  getGroupTool,
  listGroupMembersTool,
  listGroupMembershipRequestsTool,
  createGroupTool,
  updateGroupTool,
  deleteGroupTool,
  addGroupMembersByUsernameTool,
  addGroupMembersByUserIdTool,
  addGroupMembersByEmailTool,
  inviteGroupMembersByEmailTool,
  removeGroupMembersByUsernameTool,
  removeGroupMembersByUserIdTool,
  removeGroupMembersByEmailTool,
  addGroupOwnersByUsernameTool,
  addGroupOwnersByUserIdTool,
  addGroupOwnersByEmailTool,
  removeGroupOwnersByUsernameTool,
  removeGroupOwnersByUserIdTool,
  removeGroupOwnersByEmailTool,
  handleGroupMembershipRequestTool,
  requestGroupMembershipTool,
  joinGroupTool,
  leaveGroupTool,
] as const satisfies readonly ToolDefinition[];
