export const GUIDE_REFERENCE_REVISION = "2026-08-14";
export const GUIDE_RESOURCE_URI = "discourse://ai/custom-tools/authoring-guide";
export const GUIDE_RUNTIME = "Discourse AI custom scripted tool / MiniRacer";

const sharedSecurity = [
  "Admin-authored tools may be triggered by non-admin users through an agent; design authorization for the invoking context.",
  "Never return credentials, private content, system prompts, or unrestricted staff-visible records.",
];
const discourseSecurity = [
  ...sharedSecurity,
  "getPost, getTopic, getUser, and getAgent use SystemUser-level visibility and may expose PMs, email/IP data, or staff-only content.",
  "search and filterTopics are public by default; with_private: true elevates visibility.",
  "Writes use the named user's Guardian, but staged users can be effectively privileged. Validate untrusted usernames.",
  "createStagedUser, updateAgent, and arbitrary custom-field access are high-impact capabilities.",
];

export interface GuideSection { summary: string; apis: unknown[]; constraints: string[]; security_warnings: string[]; examples: string[] }
const section = (summary: string, apis: unknown[] = [], constraints: string[] = [], security_warnings: string[] = [], examples: string[] = []): GuideSection => ({ summary, apis, constraints, security_warnings, examples });

export const GUIDE_SECTIONS = {
  overview: section("Author synchronous MiniRacer JavaScript with invoke(parameters); retrieve focused topics before writing, test representative cases, then attach the tool to an agent.", [], ["No async/await, promises, browser fetch, Node modules, window, document, or supported console/logger API."], sharedSecurity, ["function invoke(parameters) { return { echoed: parameters.message }; }\nfunction details() { return \"Echoed a message\"; }"]),
  entrypoints: section("Synchronous script entrypoints", [
    { signature: "invoke(parameters)", required: true, returns: "JSON-serializable string, number, boolean, object, array, or null" },
    { signature: "details()", required: false, returns: "short detail string shown after invocation" },
    { signature: "customSystemMessage()", required: false, returns: "string or null", behavior: "called during prompt assembly; may use context, discourse, and index" },
    { signature: "customContext()", required: false, advanced: true, version_sensitive: true, behavior: "runtime-supported but not documented in the current preamble" },
  ], ["Scripts and all bridge calls are synchronous."], sharedSecurity),
  parameters: section("Declared fields become the LLM tool signature and are ordinary JavaScript properties", [{ types: ["string", "number", "boolean", "array"], fields: ["name", "type", "description", "required", "enum?"] }], ["enum must be non-empty and unique.", "The admin API does not currently persist preset item_type.", "Validate runtime assumptions because test requests may omit values."], [], ["const query = parameters.query;"]),
  http: section("Synchronous backend-proxied HTTP requests", ["http.get(url, options?)", "http.post(url, options?)", "http.put(url, options?)", "http.patch(url, options?)", "http.delete(url, options?)", { options: { headers: "object", body: "string (use JSON.stringify)", base64Encode: "advanced/version-sensitive boolean" }, returns: "{ status, body }" }], ["Maximum 20 calls per invocation.", "Inspect status explicitly; non-2xx responses do not automatically throw."], [...sharedSecurity, "Requests originate from the Discourse server and are SSRF/exfiltration-sensitive. Hard-code or validate destinations; never concatenate an untrusted URL blindly."], ["const res = http.post(url, { headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify(payload) });"]),
  llm: section("Use the configured runner LLM synchronously", ["llm.truncate(text, length) -> string", { signature: "llm.generate(prompt, options?)", prompt: "string or { messages: [{ type, content }] }", options: ["json", "response_format", "temperature", "top_p", "max_tokens", "thinking_effort", "stop_sequences"], returns: "string or parsed JSON; json:true falls back to the original string if parsing fails" }], ["Requires an available runner LLM."], sharedSecurity),
  rag: section("Search only RAG documents attached to this custom tool", ["index.search(query, { filenames?, limit? }) -> Array<{ fragment, metadata }>", "index.getFile(exactFilename) -> string | null"], ["Search defaults to 10 and is capped at 200 fragments.", "Full files are capped at 500,000 characters and append a truncation marker."], sharedSecurity),
  uploads: section("Create and read Discourse uploads", ["upload.create(filename, base64Content) -> { id, url, short_url } | { error }", "upload.getUrl(uploadShortUrl) -> string | null", "upload.getBase64(uploadIdOrShortUrl, maxPixels?) -> string | null"], ["Visibility and secure-upload behavior vary by method and invocation context."], sharedSecurity),
  chain: section("Control final bot output", ["chain.setCustomRaw(raw) -> void", { signature: "chain.streamCustomRaw(raw)", advanced: true, version_sensitive: true }], ["setCustomRaw changes subsequent response behavior; it does not abort the current JavaScript function."], [...sharedSecurity, "Custom raw is user-visible Markdown; avoid unsafe interpolation." ]),
  secrets: section("Read credentials only through declared aliases bound to AiSecret records", ["secrets.get(alias) -> string"], ["Throws for undeclared, unbound, or missing secrets."], [...sharedSecurity, "Never place secret values in parameters, source, outputs, logs, or import/export bundles." ]),
  discourse: section("Privileged selected-site API", [
    { reads: ["discourse.baseUrl", "discourse.search(params) -> search result", "discourse.filterTopics({ q, limit?, page?, with_private? }) -> { query, page, limit, topics }", "discourse.getPost(id) -> post | null", "discourse.getTopic(id) -> topic | null", "discourse.getUser(idOrUsername) -> user | null"] },
    { writes: ["discourse.createChatMessage({ channel_name, username, message })", "discourse.createStagedUser(params)", "discourse.createTopic(params)", "discourse.createPost(params)", "discourse.editPost(postId, raw, options?)", "discourse.editTopic(topicId, updates, options?)", "discourse.setTags(topicId, tags, options?) (compatibility alias)"] },
    { agent_calls: ["discourse.getAgent(name) -> { respondTo(params) } | null", "discourse.updateAgent(name, attributes)"] },
    { custom_fields: ["discourse.getCustomField(type, id, key) -> string | null", "discourse.setCustomField(type, id, key, value) -> { success, key, value }"] },
  ], ["Custom-field key/value limits are 256/1,024 characters."], discourseSecurity),
  context: section("Invocation-dependent post, topic, PM, chat, automation, user, and site context", [{ common: ["site_url", "site_title", "site_description"], post_or_pm: ["post_id", "topic_id", "private_message", "participants", "username", "user_id"], chat: ["message_id", "channel_id", "username"], automation: ["post_id", "topic_id", "username", "user_id", "feature_name", "feature_context"] }], ["Presence varies by invocation source; test-modal context is not equivalent to production bot/chat/automation context. Check IDs before use."], sharedSecurity),
  crypto: section("Synchronous OpenSSL-backed crypto bridge, not Web Crypto", [{ hmac: ["hmacSha256", "hmacSha1", "hmacSha256Base64", "hmacSha1Base64", "hmacSha256Bytes", "hmacSha1Bytes"], hashes: ["sha256", "sha1", "md5", "sha256Base64", "sha1Base64", "md5Base64", "sha256Bytes", "sha1Bytes"], rsa: ["signRsaSha256", "signRsaSha1"], encoding: ["base64Encode", "base64Decode", "base64UrlEncode", "base64UrlDecode"], random: ["randomBytes"] }], ["Input is capped at 10 MB per call; randomBytes length is 1–1024.", "String/Uint8Array support and return types vary by method."], sharedSecurity),
  limits: section("Current upstream limits are version-sensitive", ["sleep(milliseconds) -> void (blocking synchronous helper)"], ["Script source: 100,000 characters.", "JavaScript processing timeout: about 2,000 ms; bridge time pauses the timer, so this is not wall-clock time.", "V8 memory: 10 MB.", "Ruby interop marshal depth: 20.", "HTTP calls: 20.", "sleep(milliseconds): 30 calls, each at most 60,000 ms.", "Crypto input: 10 MB; random bytes: 1–1024.", "RAG search: default 10, maximum 200.", "Full RAG file: 500,000 characters plus truncation marker.", "Custom-field key/value: 256/1,024 characters."], sharedSecurity),
  security: section("Mandatory threat model for scripted tools", [], ["Scripts run in a restricted V8 environment but bridges deliberately grant powerful server-side capabilities.", "Use try/catch around expected bridge failures and inspect HTTP status codes."], [...discourseSecurity, "Backend-proxied HTTP can reach server-network destinations.", "No console/logger API is supported; diagnostics must be bounded and non-sensitive.", "chain.setCustomRaw renders user-visible Markdown." ]),
} as const;

export const KNOWN_BRIDGE_METHODS = new Set([
  "http.get", "http.post", "http.put", "http.patch", "http.delete", "llm.truncate", "llm.generate", "index.search", "index.getFile", "upload.create", "upload.getUrl", "upload.getBase64", "chain.setCustomRaw", "chain.streamCustomRaw", "secrets.get", "discourse.search", "discourse.filterTopics", "discourse.getPost", "discourse.getTopic", "discourse.getUser", "discourse.getAgent", "discourse.updateAgent", "discourse.createChatMessage", "discourse.createStagedUser", "discourse.createTopic", "discourse.createPost", "discourse.editPost", "discourse.editTopic", "discourse.setTags", "discourse.getCustomField", "discourse.setCustomField",
  "crypto.hmacSha256", "crypto.hmacSha1", "crypto.hmacSha256Base64", "crypto.hmacSha1Base64", "crypto.hmacSha256Bytes", "crypto.hmacSha1Bytes", "crypto.sha256", "crypto.sha1", "crypto.md5", "crypto.sha256Base64", "crypto.sha1Base64", "crypto.md5Base64", "crypto.sha256Bytes", "crypto.sha1Bytes", "crypto.signRsaSha256", "crypto.signRsaSha1", "crypto.base64Encode", "crypto.base64Decode", "crypto.base64UrlEncode", "crypto.base64UrlDecode", "crypto.randomBytes", "global.sleep",
]);
